basePath: /
host: localhost:port
info:
  contact:
    name: Vinícius Boscardin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Clean GO API Docs
  version: 1.0.0
paths: {}
swagger: "2.0"
